/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/isometric_office.glb --instanceall --types 
Files: public/isometric_office.glb [19.26MB] > C:\Users\Wajahat Baig\Desktop\Three.JS Blender File\isometric_office-transformed.glb [1.72MB] (91%)
Author: Companion_Cube (https://sketchfab.com/Companion_Cube)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-office-d31464eed8044190911b221648aca432
Title: Isometric office
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_8: THREE.Mesh
    Object_78: THREE.Mesh
    Object_391: THREE.Mesh
    Object_410: THREE.Mesh
    Object_432: THREE.Mesh
    Object_730: THREE.Mesh
    Object_793: THREE.Mesh
    Object_932: THREE.Mesh
    Object_938: THREE.Mesh
    Object_941: THREE.Mesh
    Object_988: THREE.Mesh
    Object_990: THREE.Mesh
    Object_992: THREE.Mesh
    Object_1043: THREE.Mesh
    Object_1045: THREE.Mesh
    Object_1071: THREE.Mesh
    Object_1140: THREE.Mesh
    Object_1223: THREE.Mesh
    Object_1226: THREE.Mesh
    Object_1229: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['floor.001']: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Poster_office_2: THREE.MeshStandardMaterial
    Poster_Pam: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    Coffee: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['01_-_Default']: THREE.MeshStandardMaterial
    Poster_office: THREE.MeshStandardMaterial
    Poster_office_3: THREE.MeshStandardMaterial
    ['02_-_Default']: THREE.MeshStandardMaterial
    Fronds: THREE.MeshStandardMaterial
    Flowers: THREE.MeshStandardMaterial
    Material_27: THREE.MeshStandardMaterial
    Projector: THREE.MeshStandardMaterial
    Office_Chair: THREE.MeshStandardMaterial
    ['wood.005']: THREE.MeshStandardMaterial
    Poster_cert: THREE.MeshStandardMaterial
    ['Poster_cert.001']: THREE.MeshStandardMaterial
    ['Poster_cert.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<React.JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: any) {
  const { nodes } = useGLTF('/isometric_office-transformed.glb') as unknown as GLTFResult
  const instances = React.useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_8,
      Object2: nodes.Object_78,
      Object3: nodes.Object_391,
      Object4: nodes.Object_410,
      Object5: nodes.Object_432,
      Object6: nodes.Object_730,
      Object7: nodes.Object_793,
      Object8: nodes.Object_932,
      Object9: nodes.Object_938,
      Object10: nodes.Object_941,
      Object11: nodes.Object_988,
      Object12: nodes.Object_990,
      Object13: nodes.Object_992,
      Object14: nodes.Object_1043,
      Object15: nodes.Object_1045,
      Object16: nodes.Object_1071,
      Object17: nodes.Object_1140,
      Object18: nodes.Object_1223,
      Object19: nodes.Object_1226,
      Object20: nodes.Object_1229,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances}>
      {(instances: any) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model({ isInteractive, ...props }: React.JSX.IntrinsicElements['group'] & { isInteractive?: boolean }) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null} rotation={[0, -Math.PI / 2, 0]} position={[18, -3, 5]} scale={2}>
      <instances.Object position={[0, -0.013, 0]} />
      <instances.Object1 position={[-10.079, -0.014, -0.121]} />
      <instances.Object2 position={[-4.321, 0.583, 2.031]} />
      <instances.Object3 position={[-9.993, 1.147, 2.515]} />
      <instances.Object4 position={[-2.078, 1.439, 6.938]} />
      <instances.Object5 position={[-4.63, 0.948, 3.339]} />
      <instances.Object6 position={[-7.088, 0.748, 4.837]} />
      <instances.Object7 position={[-6.351, 1.906, 0.45]} />
      <instances.Object8 position={[-6.933, 0.335, 1.185]} />
      <instances.Object9 position={[-7.505, 1.559, 0.009]} />
      <instances.Object10 position={[-9.931, 1.532, 0.843]} />
      <instances.Object11 position={[-9.791, -0.02, 9.661]} />
      <instances.Object12 position={[-9.795, 0.297, 9.66]} />
      <instances.Object13 position={[-9.795, 0.297, 9.66]} />
      <instances.Object14 position={[-9.996, 1.853, 8.389]} />
      <instances.Object15 position={[-8.63, 0.561, 8.524]} />
      <instances.Object16 position={[-3.822, -0.015, 9.151]} />
      <instances.Object17 position={[-3.638, -0.018, 8.559]} />
      <instances.Object18 position={[-5.381, 1.259, 8.006]} />
      <instances.Object19 position={[-5.381, 1.259, 8.495]} />
      <instances.Object20 position={[-5.381, 1.259, 7.545]} />
    </group>
  )
}

useGLTF.preload('/isometric_office-transformed.glb')
