/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/office_studiocheck.glb --instanceall --types 
Files: public/office_studiocheck.glb [61.71MB] > C:\Users\Wajahat Baig\Desktop\Three.JS Blender File\office_studiocheck-transformed.glb [4.17MB] (93%)
*/
/* eslint-disable @typescript-eslint/no-explicit-any */

import * as THREE from "three";
import React, { useContext, useRef, type JSX } from "react";
import { useGLTF, Merged, useAnimations } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type ActionName = "Front Room Holographic Book shelfAction";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    Cube002_3: THREE.Mesh;
    ["Office_table_&_chair"]: THREE.Mesh;
    Office_Laptop: THREE.Mesh;
    Office_table_Books: THREE.Mesh;
    Cube001: THREE.Mesh;
    ["L-shaped_Sofa_Set_lounge"]: THREE.Mesh;
    Lounge_Wood_Floor: THREE.Mesh;
    Longe_Wooden_Table_candles: THREE.Mesh;
    Lounge_Side_Silver_Table: THREE.Mesh;
    Lounge_Silver_Refridgerator: THREE.Mesh;
    Lounge_Black_Floral_Piece: THREE.Mesh;
    Front_Book_Shelf_room_pool: THREE.Mesh;
    Front_Room_Holographic_Book_shelf: THREE.Mesh;
    Closet_Item_Clothing_Racks: THREE.Mesh;
    Closet_Item_Seats: THREE.Mesh;
    Closet_Item_Table: THREE.Mesh;
    Closet_Item_chairs: THREE.Mesh;
    Stairs001: THREE.Mesh;
    Stairs002: THREE.Mesh;
    Stairs_Cover: THREE.Mesh;
    Longe_Wooden_Table001: THREE.Mesh;
    Front_Book_Shelf_room_Cherry_blossom_trees: THREE.Mesh;
    leaf1003: THREE.Mesh;
    leaf1023: THREE.Mesh;
    leaf2003: THREE.Mesh;
  };
  materials: {
    ["Wood Floor Gray.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    ["Pink Marble"]: THREE.MeshStandardMaterial;
    ["White leather"]: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    Paper: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshPhysicalMaterial;
    ["Pink Fabric"]: THREE.MeshStandardMaterial;
    ["Wood Floor Light Pine"]: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshPhysicalMaterial;
    ["Silver metal"]: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshStandardMaterial;
    ["Dark Steel"]: THREE.MeshStandardMaterial;
    ["White marble"]: THREE.MeshStandardMaterial;
    PaletteMaterial006: THREE.MeshStandardMaterial;
    ["Black&white marble"]: THREE.MeshStandardMaterial;
    PaletteMaterial007: THREE.MeshStandardMaterial;
    Marble: THREE.MeshStandardMaterial;
    ["Black marble"]: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["Furniture wood"]: THREE.MeshStandardMaterial;
    ["Wooden floor.003"]: THREE.MeshStandardMaterial;
    ["leaf.001"]: THREE.MeshStandardMaterial;
    leaf: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<string, any>;

const context = React.createContext({} as ContextType);

export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/office_studiocheck-transformed.glb",
  ) as unknown as GLTFResult;
  const instances = React.useMemo(
    () => ({
      Cube: nodes.Cube002_1,
      Cube1: nodes.Cube002_2,
      Cube2: nodes.Cube002_3,
      Officetablechair: nodes["Office_table_&_chair"],
      OfficeLaptop: nodes.Office_Laptop,
      OfficetableBooks: nodes.Office_table_Books,
      Cube3: nodes.Cube001,
      LshapedSofaSetlounge: nodes["L-shaped_Sofa_Set_lounge"],
      LoungeWoodFloor: nodes.Lounge_Wood_Floor,
      LongeWoodenTablecandles: nodes.Longe_Wooden_Table_candles,
      LoungeSideSilverTable: nodes.Lounge_Side_Silver_Table,
      LoungeSilverRefridgerator: nodes.Lounge_Silver_Refridgerator,
      LoungeBlackFloralPiece: nodes.Lounge_Black_Floral_Piece,
      FrontBookShelfroompool: nodes.Front_Book_Shelf_room_pool,
      FrontRoomHolographicBookshelf: nodes.Front_Room_Holographic_Book_shelf,
      ClosetItemClothingRacks: nodes.Closet_Item_Clothing_Racks,
      ClosetItemSeats: nodes.Closet_Item_Seats,
      ClosetItemTable: nodes.Closet_Item_Table,
      ClosetItemchairs: nodes.Closet_Item_chairs,
      Stairs: nodes.Stairs001,
      Stairs1: nodes.Stairs002,
      StairsCover: nodes.Stairs_Cover,
      LongeWoodenTable: nodes.Longe_Wooden_Table001,
      FrontBookShelfroomCherryblossomtrees:
        nodes.Front_Book_Shelf_room_Cherry_blossom_trees,
      Leaf: nodes.leaf1003,
      Leaf1: nodes.leaf1023,
      Leaf2: nodes.leaf2003,
    }),
    [nodes],
  );
  return (
    <Merged meshes={instances} {...(props as any)}>
      {(instances: any) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: JSX.IntrinsicElements["group"]) {
  const instances = useContext(context);
  const group = useRef<THREE.Group>(null);
  const { animations } = useGLTF(
    "/office_studiocheck-transformed.glb",
  ) as unknown as GLTFResult;
  useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube002" position={[0, 7.5, 0]}>
          <instances.Cube name="Cube002_1" castShadow receiveShadow />
          <instances.Cube1 name="Cube002_2" castShadow receiveShadow />
          <instances.Cube2 name="Cube002_3" castShadow receiveShadow />
        </group>
        <instances.Officetablechair
          name="Office_table_&_chair"
          position={[3.732, 0.738, -0.625]}
          scale={[1.647, 0.83, 0.83]}
          castShadow
          receiveShadow
        />
        <instances.OfficeLaptop
          name="Office_Laptop"
          position={[3.806, 1.653, 0.634]}
          scale={[0.291, 0.24, 0.24]}
          castShadow
          receiveShadow
        />
        <instances.OfficetableBooks
          name="Office_table_Books"
          position={[2.897, 1.653, 0.479]}
          scale={[0.184, 0.184, 0.24]}
          castShadow
          receiveShadow
        />
        <instances.Cube3 name="Cube001" position={[0, 7.5, 0]} castShadow receiveShadow />
        <instances.LshapedSofaSetlounge
          name="L-shaped_Sofa_Set_lounge"
          position={[-1.389, 0.959, 1.148]}
          scale={[2.214, 0.897, 0.897]}
          castShadow
          receiveShadow
        />
        <instances.LoungeWoodFloor
          name="Lounge_Wood_Floor"
          position={[-1.26, 0.959, -0.33]}
          scale={[2.157, 2.157, 2.048]}
          castShadow
          receiveShadow
        />
        <instances.LongeWoodenTablecandles
          name="Longe_Wooden_Table_candles"
          position={[-1.713, 0.977, -0.811]}
          scale={[1.17, 1.17, 0.652]}
          castShadow
          receiveShadow
        />
        <instances.LoungeSideSilverTable
          name="Lounge_Side_Silver_Table"
          position={[-3.784, 1.252, 1.746]}
          scale={0.273}
          castShadow
          receiveShadow
        />
        <instances.LoungeSilverRefridgerator
          name="Lounge_Silver_Refridgerator"
          position={[-3.845, 0.906, -3.583]}
          scale={[0.513, 0.587, 0.513]}
          castShadow
          receiveShadow
        />
        <instances.LoungeBlackFloralPiece
          name="Lounge_Black_Floral_Piece"
          position={[-0.06, 0.906, -3.583]}
          scale={0.235}
          castShadow
          receiveShadow
        />
        <instances.FrontBookShelfroompool
          name="Front_Book_Shelf_room_pool"
          position={[9.156, 0.937, 6.994]}
          scale={[1.95, 1.783, 3.261]}
          castShadow
          receiveShadow
        />
        <instances.FrontRoomHolographicBookshelf
          name="Front_Room_Holographic_Book_shelf"
          position={[12.297, 2.779, 6.88]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[1.626, 0.889, 2.903]}
          castShadow
          receiveShadow
        />
        <instances.ClosetItemClothingRacks
          name="Closet_Item_Clothing_Racks"
          position={[-1.53, 5.824, -2.278]}
          scale={1.549}
          castShadow
          receiveShadow
        />
        <instances.ClosetItemSeats
          name="Closet_Item_Seats"
          position={[-1.119, 5.823, -2.636]}
          scale={0.818}
          castShadow
          receiveShadow
        />
        <instances.ClosetItemTable
          name="Closet_Item_Table"
          position={[0.148, 6.918, 1.23]}
          scale={[1.805, 1.664, 0.704]}
          castShadow
          receiveShadow
        />
        <instances.ClosetItemchairs
          name="Closet_Item_chairs"
          position={[-0.968, 5.823, -0.147]}
          scale={0.355}
          castShadow
          receiveShadow
        />
        <instances.Stairs
          name="Stairs001"
          position={[-7.987, -3.814, -0.981]}
          scale={[0.14, 0.342, 0.14]}
          castShadow
          receiveShadow
        />
        <instances.Stairs1
          name="Stairs002"
          position={[-7.987, -1.772, -0.981]}
          scale={[0.706, 0.992, 0.706]}
          castShadow
          receiveShadow
        />
        <instances.StairsCover
          name="Stairs_Cover"
          position={[-7.986, -1.772, -0.986]}
          scale={1.733}
          castShadow
          receiveShadow
        />
        <instances.LongeWoodenTable
          name="Longe_Wooden_Table001"
          position={[-1.713, 0.977, -0.811]}
          scale={[1.17, 1.17, 0.652]}
          castShadow
          receiveShadow
        />
        <instances.FrontBookShelfroomCherryblossomtrees
          name="Front_Book_Shelf_room_Cherry_blossom_trees"
          position={[11.157, 0.937, 4.35]}
          scale={[0.389, 0.355, 0.389]}
          castShadow
          receiveShadow
        />
        <instances.Leaf
          name="leaf1003"
          position={[9.14, 2.103, 7.64]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.363, 0.332, 0.363]}
          castShadow
          receiveShadow
        />
        <instances.Leaf1
          name="leaf1023"
          position={[9.14, 2.103, 7.64]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.363, 0.332, 0.363]}
          castShadow
          receiveShadow
        />
        <instances.Leaf2
          name="leaf2003"
          position={[9.84, 2.532, 7.829]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.363, 0.332, 0.363]}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("/office_studiocheck-transformed.glb");
